//import * as events from './events'
//import * as observables from './observables'
//import * as operators from './operators'
//import * as promises from './promises'
//import * as transforming from './transforming'
//import * as buffers from './buffers'
//import * as debounce from './debounce'
//import * as merge from './merge'
//import * as concat from './concat'
//import * as mergeMap from './mergeMap'
//import * as concatMap from './concatMap'
//import * as switchMap from './switchMap'
//import * as zip from './zip'
//import * as utility from './utility'
//import * as subject from './subject'
//import * as error from './error'
//import * as ex1 from './paradigm/example_01'
//import * as ex2 from './paradigm/example_02'
//import * as ex3 from './paradigm/example_03'
//import * as ex4 from './paradigm/example_04'
//import * as ch1 from './mastering/replay subject'
//import * as ex5 from './paradigm/do and finally'
//import * as ex6 from './paradigm/merge and concat'
//import * as ex7 from './paradigm/map, mergeMap, switchMap'
//import * as ex8 from './paradigm/scan reduce'
//import * as ex9 from './paradigm/buffers'
//import * as spaceship from './mastering/spaceshipt game'
import * as helloCanvas from './canvas/helloCanvas'